##read tree file##
library(picante)
library(ape)
library(vegan)
library(ade4)
library(GUniFrac)
setwd("D:/a lab/aProjects/Stanford/water_32 vs 32")
a<-read.tree("Galaxy3-[FastTree.nwk].nwk", tree.names = NULL) ##It's the tree file generated by our pipeline##
tree<-root(a,1,r=T)  ##add a root## #Please read the introduction file of package picante, some function need rooted trees, BE CAREFUL!!!###
is.rooted(tree)  ##check if rooted##

##read community file##note cut ghost species
comm<-read.table("OTU_no annotation.csv",header=T,sep=",",row.names=1)
dim(comm)
community<-t(comm)   ##Comm should be used ##All=read.table(file.choose(),header=T,sep=",")
combined <- match.phylo.comm(tree, community)
Tree<- combined$phy
Comm<- combined$comm
dim(Comm)


#phylogenetic diversity
PD<-pd(Comm, Tree, include.root=TRUE)
write.csv(PD,file="phylogenetic diversity_16S.csv")


#Shannon and Simpson...
H <- diversity(Comm)
simp <- diversity(Comm, "simpson")
invsimp <- diversity(Comm, "inv")
## Species richness (S) and Pielou's evenness (J):

S <- specnumber(Comm) ## rowSums(BCI > 0) does the same...
J <- H/log(S)
taxadiv<-cbind(H,simp,invsimp,S,J)
write.csv(taxadiv,file="taxa diversity.csv")